version: "3.7"

services:
  tracetogether_service:
    build: ./
    container_name: tracetogether_service
    volumes:
      - database:/app/data
    restart: always
    ports:
      - "50051:50051"
volumes:
  database: