# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Tracetogether_pb2 as Tracetogether__pb2


class TracetogetherStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.check_in = channel.unary_unary(
                '/Tracetogether/check_in',
                request_serializer=Tracetogether__pb2.CheckIn_Request.SerializeToString,
                response_deserializer=Tracetogether__pb2.CheckIn_Reply.FromString,
                )
        self.check_out = channel.unary_unary(
                '/Tracetogether/check_out',
                request_serializer=Tracetogether__pb2.CheckOut_Request.SerializeToString,
                response_deserializer=Tracetogether__pb2.CheckOut_Reply.FromString,
                )
        self.check_in_grp = channel.unary_unary(
                '/Tracetogether/check_in_grp',
                request_serializer=Tracetogether__pb2.CheckIn_Grp_Request.SerializeToString,
                response_deserializer=Tracetogether__pb2.CheckIn_Grp_Reply.FromString,
                )
        self.check_out_grp = channel.unary_unary(
                '/Tracetogether/check_out_grp',
                request_serializer=Tracetogether__pb2.CheckOut_Grp_Request.SerializeToString,
                response_deserializer=Tracetogether__pb2.CheckOut_Grp_Reply.FromString,
                )
        self.get_history = channel.unary_unary(
                '/Tracetogether/get_history',
                request_serializer=Tracetogether__pb2.History_Request.SerializeToString,
                response_deserializer=Tracetogether__pb2.History_Reply.FromString,
                )
        self.flag_cases = channel.unary_unary(
                '/Tracetogether/flag_cases',
                request_serializer=Tracetogether__pb2.Flag_Request.SerializeToString,
                response_deserializer=Tracetogether__pb2.Flag_Reply.FromString,
                )


class TracetogetherServicer(object):
    """Missing associated documentation comment in .proto file."""

    def check_in(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def check_out(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def check_in_grp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def check_out_grp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_history(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def flag_cases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TracetogetherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'check_in': grpc.unary_unary_rpc_method_handler(
                    servicer.check_in,
                    request_deserializer=Tracetogether__pb2.CheckIn_Request.FromString,
                    response_serializer=Tracetogether__pb2.CheckIn_Reply.SerializeToString,
            ),
            'check_out': grpc.unary_unary_rpc_method_handler(
                    servicer.check_out,
                    request_deserializer=Tracetogether__pb2.CheckOut_Request.FromString,
                    response_serializer=Tracetogether__pb2.CheckOut_Reply.SerializeToString,
            ),
            'check_in_grp': grpc.unary_unary_rpc_method_handler(
                    servicer.check_in_grp,
                    request_deserializer=Tracetogether__pb2.CheckIn_Grp_Request.FromString,
                    response_serializer=Tracetogether__pb2.CheckIn_Grp_Reply.SerializeToString,
            ),
            'check_out_grp': grpc.unary_unary_rpc_method_handler(
                    servicer.check_out_grp,
                    request_deserializer=Tracetogether__pb2.CheckOut_Grp_Request.FromString,
                    response_serializer=Tracetogether__pb2.CheckOut_Grp_Reply.SerializeToString,
            ),
            'get_history': grpc.unary_unary_rpc_method_handler(
                    servicer.get_history,
                    request_deserializer=Tracetogether__pb2.History_Request.FromString,
                    response_serializer=Tracetogether__pb2.History_Reply.SerializeToString,
            ),
            'flag_cases': grpc.unary_unary_rpc_method_handler(
                    servicer.flag_cases,
                    request_deserializer=Tracetogether__pb2.Flag_Request.FromString,
                    response_serializer=Tracetogether__pb2.Flag_Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Tracetogether', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tracetogether(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def check_in(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tracetogether/check_in',
            Tracetogether__pb2.CheckIn_Request.SerializeToString,
            Tracetogether__pb2.CheckIn_Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def check_out(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tracetogether/check_out',
            Tracetogether__pb2.CheckOut_Request.SerializeToString,
            Tracetogether__pb2.CheckOut_Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def check_in_grp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tracetogether/check_in_grp',
            Tracetogether__pb2.CheckIn_Grp_Request.SerializeToString,
            Tracetogether__pb2.CheckIn_Grp_Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def check_out_grp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tracetogether/check_out_grp',
            Tracetogether__pb2.CheckOut_Grp_Request.SerializeToString,
            Tracetogether__pb2.CheckOut_Grp_Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_history(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tracetogether/get_history',
            Tracetogether__pb2.History_Request.SerializeToString,
            Tracetogether__pb2.History_Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def flag_cases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tracetogether/flag_cases',
            Tracetogether__pb2.Flag_Request.SerializeToString,
            Tracetogether__pb2.Flag_Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
